- name: Copy home directory Files.
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - { src: roles/homedirectory/files/.config, dest: ~/ }
  - { src: roles/homedirectory/files/.bash_profile, dest: ~/ }
  - { src: roles/homedirectory/files/.gitconfig, dest: ~/ }
  - { src: roles/homedirectory/files/.tmux.conf, dest: ~/ }

- name: git_clone_bash_it
  git:
    repo: "git@github.com:Bash-it/bash-it.git"
    dest: "~/bash-it"
 
